### ISSUE TITLE
UnknownHostException when starting CLI

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/score#32]
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'io.cloudslang.worker.management.WorkerRegistration#0': Invocation of init method failed; nested exception is java.net.UnknownHostException: alonbecker.local: alonbecker.local: nodename nor servname provided, or not known 
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) 
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407) 

might be related to : 
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7180557

**Comment by meirwah** [comment]
User encountered it on OSX
